# Generated by Django 2.0.10 on 2019-02-07 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('impact_level', models.IntegerField()),
                ('num_times_read', models.IntegerField()),
                ('date_last_read', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
