# Generated by Django 2.0.10 on 2019-02-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='num_times_read',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
