# Generated by Django 2.2.2 on 2019-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20190206_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='impact_level',
            field=models.IntegerField(null=True),
        ),
    ]
